Fix "_WIN32_WINNT" redefined warning
This fixes the following GCC warning:

 /home/runner/work/portaudio/portaudio/test/patest_dsound_find_best_latency_params.c:43: error: "_WIN32_WINNT" redefined [-Werror]
   43 | #define  _WIN32_WINNT 0x0501 /* for GetNativeSystemInfo */
      |
In file included from /usr/share/mingw-w64/include/corecrt.h:10,
                 from /usr/share/mingw-w64/include/corecrt_stdio_config.h:10,
                 from /usr/share/mingw-w64/include/stdio.h:9,
                 from /home/runner/work/portaudio/portaudio/test/patest_dsound_find_best_latency_params.c:39:
/usr/share/mingw-w64/include/_mingw.h:233: note: this is the location of the previous definition
  233 | #define _WIN32_WINNT 0x502
      |

I am proactively fixing this warning because GCC preprocessor warnings
seem difficult to suppress.